// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// import "dotenv/config";
// import { defineConfig } from "prisma/config";

// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   migrations: {
//     path: "prisma/migrations",
//   },
//   datasource: {
//     url: process.env["postgresql://postgres:pratuuu16@localhost:5432/resume_db?schema=public"],
//   },
// });
import "dotenv/config";
import { defineConfig } from "@prisma/config"; // Ensure this matches your installed version

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // PASS THE STRING DIRECTLY, NOT THROUGH process.env
    url: "postgresql://postgres:pratuuu16@localhost:5432/resume_db?schema=public",
  },
});